# Generated by Django 5.1.6 on 2025-03-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_collection_featured_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
