# Generated by Django 5.1.6 on 2025-03-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_cart_cartitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
